export const TIMEOUTS = {
  DEFAULT: 10000,
  CONTENT_EXTRACTION: 6000,
  BROWSER_MAX: 8000,
  ENGINE_FALLBACK: 4000,
  SELECTOR_WAIT: 2000,
  JS_RENDER_WAIT: 1500,
  SHORT_DELAY: 1000,
  RETRY_DELAY: 500,
} as const;

export const QUALITY = {
  MIN_ACCEPTABLE: 0.3,
  EXCELLENT: 0.8,
  DEFAULT_SCORE: 0.5,
  PHRASE_MATCH_BONUS: 0.3,
} as const;

export const CONTENT_LIMITS = {
  MAX_DEFAULT: 500000,
  CLEAN_TEXT_DEFAULT: 10000,
  CONTENT_PREVIEW_DEFAULT: 500,
  QUERY_MAX_LENGTH: 1000,
  LLAMA_CONTENT_LIMIT: 2000,
  ROBUST_MODEL_THRESHOLD: 5000,
  MIN_CONTENT_LENGTH: 100,
} as const;

export const SEARCH = {
  DEFAULT_RESULTS: 5,
  MAX_RESULTS: 10,
  QUERY_DEBUG_TRUNCATE: 30,
  EXTRA_RESULTS_FACTOR: 2,
  EXTRA_RESULTS_BUFFER: 2,
} as const;

export const BROWSER = {
  MAX_INSTANCES: 3,
  FALLBACK_THRESHOLD: 3,
  CONCURRENT_LIMIT: 5,
  EXTRACTION_TIMEOUT: 8000,
} as const;

export const BROWSER_BY_OS = {
  darwin: ['chromium', 'firefox', 'webkit'] as const,
  default: ['chromium', 'firefox'] as const,
} as const;

export const RANDOM_BEHAVIOR = {
  HAS_TOUCH_PROBABILITY: 0.7,
  IS_MOBILE_PROBABILITY: 0.8,
  DEVICE_SCALE_PROBABILITY: 0.5,
  CLICK_PROBABILITY: 0.7,
  MOUSE_MOVE_MAX_X: 100,
  MOUSE_MOVE_MAX_Y: 100,
  SCROLL_MAX_Y: 500,
  DELAY_MIN: 500,
  DELAY_MAX: 1500,
  CLICK_TIMEOUT: 1000,
} as const;

export const VALIDATION = {
  MIN_URL_LENGTH: 10,
  MIN_TITLE_LENGTH: 5,
  MAX_TITLE_LENGTH: 200,
  MIN_SNIPPET_LENGTH: 20,
} as const;
